#!/usr/bin/env python3
"""Test overlay_from_log reconstruction matches live overlay.

Compares the overlay generated by overlay_from_log.py against the live
overlay saved in 1280x480 debug images (raw|overlay side by side).

Any pixel difference outside the digit re-render area is a failure.
The digit re-render area (digit images + gap debug) differs on skipped
frames because these images are re-extracted from the saved raw frame
rather than the cached detection frame.

Images saved before the draw_display_overlay refactor (commit 6236153)
are skipped as LEGACY — the overlay rendering code has changed.

Usage:
    python scripts/test_overlay.py
    python scripts/test_overlay.py logs/manual_20260204_090629.png
"""
import cv2
import glob
import numpy as np
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, PROJECT_ROOT)

from scripts.overlay_from_log import parse_txt, draw_overlay

# Digit re-render region: re-extracted digit images + gap debug
# (corrected panel image + brightness histogram).
# These are placed in the top-right area of the 640-wide overlay frame.
# Labels and reading text use data from the txt file and must match exactly.
RERENDER_X_MIN = 340   # leftmost edge of gap debug image
RERENDER_Y_MAX = 155    # bottom of gap debug (corrected_h + hist_h + margin)

# Overlay refactor commit — images saved before this have different rendering
REFACTOR_COMMIT = '6236153'


def test_pair(png_path, txt_path, verbose=True):
    """Test one png+txt pair.

    Returns:
        'pass'   - no diff outside digit re-render area
        'legacy' - saved before overlay refactor, skipped
        'fail'   - unexpected diff
        None     - skipped (wrong size, unreadable)
    """
    name = os.path.basename(png_path)
    img = cv2.imread(png_path)
    if img is None:
        if verbose:
            print(f"  SKIP: cannot read {name}")
        return None

    h, w = img.shape[:2]
    if w != 1280 or h != 480:
        if verbose:
            print(f"  SKIP: {name} is {w}x{h}, need 1280x480")
        return None

    data, sections = parse_txt(txt_path)

    # Skip pre-refactor images — overlay rendering has changed
    code_ver = str(data.get('code_version', ''))
    if code_ver and code_ver != REFACTOR_COMMIT:
        if verbose:
            print(f"  LEGACY: {name}  code_version={code_ver}")
        return 'legacy'

    raw = img[:, :640].copy()
    live_overlay = img[:, 640:]

    # Reconstruct overlay
    recon_overlay = draw_overlay(raw, data)

    # Compare
    diff = cv2.absdiff(live_overlay, recon_overlay)
    diff_mask = np.any(diff > 0, axis=2)
    diff_total = np.count_nonzero(diff_mask)

    # Mask out allowed digit re-render region (top-right)
    outside_mask = diff_mask.copy()
    outside_mask[:RERENDER_Y_MAX, RERENDER_X_MIN:] = False
    diff_outside = np.count_nonzero(outside_mask)

    skipped = data.get('frame_skipped', 'no')

    if diff_outside == 0:
        if verbose:
            print(f"  PASS: {name}  skip={skipped}  diff={diff_total}")
        return 'pass'

    ys, xs = np.where(outside_mask)
    y_min, y_max = ys.min(), ys.max()
    x_min, x_max = xs.min(), xs.max()

    if verbose:
        print(f"  FAIL: {name}  skip={skipped}  "
              f"diff={diff_total}  outside={diff_outside}  "
              f"at x=[{x_min}-{x_max}] y=[{y_min}-{y_max}]")

    return 'fail'


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    logs_dir = os.path.join(PROJECT_ROOT, 'logs')

    if args:
        # Test specific file(s)
        pairs = []
        for path in args:
            base = path.rsplit('.', 1)[0]
            txt = base + '.txt'
            png = base + '.png'
            if os.path.exists(txt) and os.path.exists(png):
                pairs.append((png, txt))
            else:
                print(f"Error: Need both {os.path.basename(png)} and "
                      f"{os.path.basename(txt)}")
                sys.exit(1)
    else:
        # Find all 1280x480 pairs in logs/
        pairs = []
        for txt in sorted(glob.glob(os.path.join(logs_dir, '*.txt'))):
            png = txt[:-4] + '.png'
            if not os.path.exists(png):
                continue
            img = cv2.imread(png)
            if img is not None and img.shape == (480, 1280, 3):
                pairs.append((png, txt))

    if not pairs:
        print("No testable pairs found")
        sys.exit(1)

    print(f"Testing {len(pairs)} overlay pair(s)")
    counts = {'pass': 0, 'fail': 0, 'skip': 0, 'legacy': 0}

    for png_path, txt_path in pairs:
        result = test_pair(png_path, txt_path)
        if result is None:
            counts['skip'] += 1
        elif result == 'pass':
            counts['pass'] += 1
        elif result == 'legacy':
            counts['legacy'] += 1
        else:
            counts['fail'] += 1

    print(f"\nResults: {counts['pass']} passed, {counts['fail']} failed, "
          f"{counts['legacy']} legacy, {counts['skip']} skipped")
    sys.exit(1 if counts['fail'] > 0 else 0)


if __name__ == '__main__':
    main()
